import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  ArrowRight, X, CheckCircle2, Upload, Cpu, ShieldCheck,
  GitBranch, Send, BarChart3, MapPin, Trash2, Droplet,
  Zap, Flame, Car, Wrench, AlertTriangle, Waves,
  Quote, TrendingUp,
} from 'lucide-react'
import HeroSection      from '../components/HeroSection'
import FeatureGrid      from '../components/FeatureGrid'
import AiDemoSection    from '../components/AiDemoSection'
import DashboardPreview from '../components/DashboardPreview'

/* ─── Trust Metrics ─── */
const metrics = [
  { value: '1,200+', label: 'Complaints Processed',  color: 'text-emerald-600' },
  { value: '95%',    label: 'AI Routing Accuracy',   color: 'text-sky-600'     },
  { value: '10+',    label: 'Departments Supported', color: 'text-violet-600'  },
  { value: '< 48h',  label: 'Avg. Resolution Time',  color: 'text-amber-600'   },
]

function TrustMetrics() {
  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {metrics.map(({ value, label, color }, i) => (
          <motion.div
            key={label}
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.08 }}
            className="flex flex-col items-center gap-1 rounded-2xl bg-slate-50 py-5 px-3 text-center"
          >
            <p className={`text-3xl font-bold ${color}`}>{value}</p>
            <p className="text-xs font-medium text-slate-500">{label}</p>
          </motion.div>
        ))}
      </div>
    </section>
  )
}

/* ─── Problem vs Solution ─── */
const problems = [
  'Find the right department manually',
  'Write complaint text yourself',
  'Multiple office visits required',
  'No transparency or tracking',
  'Weeks of delayed response',
]
const solutions = [
  'Upload one photo — AI does the rest',
  'Complaint auto-generated by AI',
  'Submit in under 30 seconds online',
  'Real-time tracking from day one',
  'Routed instantly, resolved faster',
]

function ProblemSolution() {
  return (
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div className="grid lg:grid-cols-2">
        {/* Problem */}
        <div className="border-b border-slate-200 p-8 lg:border-b-0 lg:border-r">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-600">
            <X className="h-3.5 w-3.5" /> Traditional System
          </div>
          <h3 className="mb-5 text-xl font-bold text-slate-900">The old way is broken.</h3>
          <ul className="space-y-3">
            {problems.map((p) => (
              <li key={p} className="flex items-start gap-3 text-sm text-slate-600">
                <X className="mt-0.5 h-4 w-4 shrink-0 text-rose-400" />
                {p}
              </li>
            ))}
          </ul>
        </div>

        {/* Solution */}
        <div className="bg-gradient-to-br from-emerald-50/60 to-white p-8">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700">
            <CheckCircle2 className="h-3.5 w-3.5" /> JanSetu AI
          </div>
          <h3 className="mb-5 text-xl font-bold text-slate-900">The smarter way forward.</h3>
          <ul className="space-y-3">
            {solutions.map((s) => (
              <li key={s} className="flex items-start gap-3 text-sm text-slate-700">
                <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />
                {s}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  )
}

/* ─── How It Works Timeline ─── */
const howSteps = [
  { icon: Upload,       title: 'Upload Photo',        desc: 'Capture any civic issue and upload it from your phone or browser.',          color: 'bg-emerald-500' },
  { icon: Cpu,          title: 'AI Analysis',          desc: 'AI identifies the issue type, generates a caption, and assesses severity.',   color: 'bg-sky-500'     },
  { icon: ShieldCheck,  title: 'Severity Assessment',  desc: 'Your selected severity is locked in — AI confirms and validates it.',         color: 'bg-violet-500'  },
  { icon: GitBranch,    title: 'Department Routing',   desc: 'Complaint is automatically routed to the correct government department.',     color: 'bg-amber-500'   },
  { icon: Send,         title: 'Complaint Submission', desc: 'Review the AI-generated complaint and submit with one click.',               color: 'bg-rose-500'    },
  { icon: BarChart3,    title: 'Track Resolution',     desc: 'Monitor progress through every stage until the issue is resolved.',          color: 'bg-teal-500'    },
]

function HowItWorksSection() {
  return (
    <section id="how-it-works" className="space-y-8">
      <div className="text-center">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-600">Process</p>
        <h2 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">How it works in 6 steps.</h2>
        <p className="mt-2 text-sm text-slate-500">From photo to resolution — the complete AI-powered complaint lifecycle.</p>
      </div>

      <div className="relative">
        {/* Vertical line */}
        <div className="absolute left-5 top-0 hidden h-full w-px bg-slate-200 sm:block lg:left-1/2" />

        <div className="space-y-6">
          {howSteps.map((step, i) => {
            const Icon = step.icon
            const isRight = i % 2 === 1
            return (
              <motion.div
                key={step.title}
                initial={{ opacity: 0, x: isRight ? 24 : -24 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: '-40px' }}
                transition={{ duration: 0.4 }}
                className={`relative flex gap-4 sm:gap-6 lg:w-1/2 ${isRight ? 'lg:ml-auto lg:flex-row-reverse' : ''}`}
              >
                {/* Step dot */}
                <div className={`relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${step.color} shadow-md`}>
                  <Icon className="h-5 w-5 text-white" />
                </div>

                <div className="flex-1 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className={`flex h-5 w-5 items-center justify-center rounded-full ${step.color} text-[10px] font-bold text-white`}>
                      {i + 1}
                    </span>
                    <h3 className="text-sm font-bold text-slate-900">{step.title}</h3>
                  </div>
                  <p className="text-xs leading-relaxed text-slate-500">{step.desc}</p>
                </div>
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  )
}

/* ─── Issue Categories ─── */
const categories = [
  { icon: MapPin,        label: 'Road Damage',           dept: 'Municipal / PWD',    color: 'bg-orange-50  text-orange-600  border-orange-100'  },
  { icon: Trash2,        label: 'Garbage',               dept: 'Sanitation Dept.',   color: 'bg-green-50   text-green-600   border-green-100'   },
  { icon: Droplet,       label: 'Water Leakage',         dept: 'Water Department',   color: 'bg-sky-50     text-sky-600     border-sky-100'     },
  { icon: Zap,           label: 'Electric Hazards',      dept: 'Electricity Board',  color: 'bg-yellow-50  text-yellow-600  border-yellow-100'  },
  { icon: Car,           label: 'Traffic Issues',        dept: 'Traffic Police',     color: 'bg-blue-50    text-blue-600    border-blue-100'    },
  { icon: Wrench,        label: 'Public Property',       dept: 'Municipal Corp.',    color: 'bg-slate-50   text-slate-600   border-slate-200'   },
  { icon: Flame,         label: 'Fire Hazards',          dept: 'Fire Brigade',       color: 'bg-rose-50    text-rose-600    border-rose-100'    },
  { icon: Waves,         label: 'Drainage Problems',     dept: 'Public Works',       color: 'bg-teal-50    text-teal-600    border-teal-100'    },
]

function CategoriesSection() {
  return (
    <section className="space-y-6">
      <div className="text-center">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-600">Coverage</p>
        <h2 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">Supported issue categories.</h2>
        <p className="mt-2 text-sm text-slate-500">AI automatically maps every issue to the correct government department.</p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {categories.map(({ icon: Icon, label, dept, color }, i) => (
          <motion.div
            key={label}
            initial={{ opacity: 0, scale: 0.96 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.05 }}
            className={`flex items-center gap-3 rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-sm ${color}`}
          >
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/80 shadow-sm">
              <Icon className="h-4.5 w-4.5 h-[18px] w-[18px]" />
            </div>
            <div>
              <p className="text-sm font-semibold">{label}</p>
              <p className="text-[11px] opacity-70">{dept}</p>
            </div>
          </motion.div>
        ))}
      </div>
    </section>
  )
}

/* ─── Testimonials ─── */
const testimonials = [
  {
    quote: "I reported a pothole that had been ignored for months. JanSetu AI routed it to the right department in seconds. It was repaired within 3 days.",
    name: 'Priya Sharma',
    role: 'Resident, Indore',
    avatar: 'PS',
    color: 'bg-emerald-100 text-emerald-700',
  },
  {
    quote: "As a municipal officer, the admin dashboard has transformed how we handle complaints. We can now prioritize critical issues and track resolution in real time.",
    name: 'Rajesh Verma',
    role: 'Municipal Officer, Nagpur',
    avatar: 'RV',
    color: 'bg-sky-100 text-sky-700',
  },
  {
    quote: "No more writing long complaint letters or visiting offices. I just upload a photo and the AI handles everything. This is how government services should work.",
    name: 'Anita Patel',
    role: 'Citizen, Bhopal',
    avatar: 'AP',
    color: 'bg-violet-100 text-violet-700',
  },
]

function TestimonialsSection() {
  return (
    <section className="space-y-6">
      <div className="text-center">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-600">Testimonials</p>
        <h2 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">Trusted by citizens and officials.</h2>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        {testimonials.map(({ quote, name, role, avatar, color }, i) => (
          <motion.div
            key={name}
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1 }}
            className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
          >
            <Quote className="h-5 w-5 text-slate-200" />
            <p className="flex-1 text-sm leading-relaxed text-slate-600">"{quote}"</p>
            <div className="flex items-center gap-3">
              <div className={`flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold ${color}`}>
                {avatar}
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-900">{name}</p>
                <p className="text-xs text-slate-400">{role}</p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </section>
  )
}

/* ─── Final CTA ─── */
function FinalCTA() {
  return (
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-10 text-center shadow-2xl lg:p-16">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -left-24 -top-24 h-72 w-72 rounded-full bg-emerald-500/10 blur-3xl" />
        <div className="absolute -bottom-24 -right-24 h-72 w-72 rounded-full bg-sky-500/8 blur-3xl" />
      </div>
      <div className="relative space-y-6">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <span className="inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold text-emerald-400">
            <TrendingUp className="h-3.5 w-3.5" /> Join thousands of citizens
          </span>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.1 }}
          className="space-y-3"
        >
          <h2 className="text-3xl font-bold text-white sm:text-4xl">Ready to Improve Your City?</h2>
          <p className="mx-auto max-w-md text-base text-slate-400">
            Report civic issues in under 30 seconds and let AI handle the rest.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.2 }}
          className="flex flex-wrap justify-center gap-3"
        >
          <Link
            to="/new"
            className="inline-flex items-center gap-2 rounded-full bg-emerald-500 px-7 py-3 text-sm font-bold text-white shadow-lg shadow-emerald-500/30 transition hover:bg-emerald-400"
          >
            Report Issue <ArrowRight className="h-4 w-4" />
          </Link>
          <Link
            to="/tracking"
            className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-800/60 px-7 py-3 text-sm font-bold text-slate-200 backdrop-blur-sm transition hover:border-slate-500 hover:bg-slate-800"
          >
            Track Complaint
          </Link>
        </motion.div>
      </div>
    </section>
  )
}

/* ─── Landing Page ─── */
export default function Landing() {
  return (
    <div className="space-y-10 pb-16">
      <HeroSection />
      <TrustMetrics />
      <ProblemSolution />
      <HowItWorksSection />
      <CategoriesSection />
      <FeatureGrid />
      <AiDemoSection />
      <DashboardPreview />
      <TestimonialsSection />
      <FinalCTA />
    </div>
  )
}
